package in.foodcart.service;
import in.foodcart.domain.*; import java.math.BigDecimal; import java.util.*;
public class OrderService {
 public record CartLine(String menuItemId,int quantity,BigDecimal displayedPrice) {}
 public record Checkout(String vendorId,String customerId,String mobile,String type,List<CartLine> lines) {}
 public interface Catalog { Vendor vendor(String id); MenuItem item(String vendorId,String itemId); }
 public Order create(Checkout checkout,Catalog catalog,long number){ Vendor v=catalog.vendor(checkout.vendorId()); if(v==null||v.status()!=VendorStatus.OPEN) throw new IllegalStateException("This vendor is currently closed."); List<OrderItemSnapshot> snapshots=new ArrayList<>(); for(CartLine line:checkout.lines()){if(line.quantity()<1)throw new IllegalArgumentException("Quantity must be positive");MenuItem item=catalog.item(v.id(),line.menuItemId());if(item==null||!item.active()||!item.available())throw new IllegalStateException("An item is no longer available."); if(line.displayedPrice()!=null&&item.price().compareTo(line.displayedPrice())!=0)throw new IllegalStateException(item.name()+" price has changed. Please review your cart.");snapshots.add(new OrderItemSnapshot(item.id(),item.name(),item.price(),line.quantity(),item.price().multiply(BigDecimal.valueOf(line.quantity()))));} if(snapshots.isEmpty())throw new IllegalArgumentException("Cart is empty"); BigDecimal total=snapshots.stream().map(OrderItemSnapshot::lineTotal).reduce(BigDecimal.ZERO,BigDecimal::add); return new Order(UUID.randomUUID().toString(),number,v.id(),checkout.customerId(),checkout.mobile(),OrderStatus.PLACED,List.copyOf(snapshots),total,checkout.type(),"CASH"); }
 public Order transition(Order order,String authenticatedVendorId,OrderStatus target){if(!order.vendorId().equals(authenticatedVendorId))throw new SecurityException("Order does not belong to this vendor");if(!allowed(order.status(),target))throw new IllegalStateException("Invalid order status transition");return new Order(order.id(),order.orderNumber(),order.vendorId(),order.customerId(),order.customerMobile(),target,order.items(),order.total(),order.type(),order.paymentMethod());}
 private boolean allowed(OrderStatus from,OrderStatus to){return (from==OrderStatus.PLACED&&(to==OrderStatus.ACCEPTED||to==OrderStatus.REJECTED))||(from==OrderStatus.ACCEPTED&&to==OrderStatus.PREPARING)||(from==OrderStatus.PREPARING&&(to==OrderStatus.READY||to==OrderStatus.COMPLETED))||(from==OrderStatus.READY&&to==OrderStatus.COMPLETED);}
}
